title: Support extern
# site_url: https://wiki.mycompany.com
description: Häufig gestellte Fragen und Anleitungen für die Nutzung unserer Dienste.

remote_theme: pages-themes/cayman@v0.2.0
theme:
  name: cayman
  palette:
    primary: orange
    accent: bordeaux
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - toc.integrate

nav:
  - Home: index.md
  - Office 365:
    - Overview: office365/index.md
  - WebUntis:
    - Overview: webuntis/index.md
    - Manual - User Roles: webuntis/students-login.md
    - Manual - Security: webuntis/parents-login.md
  - iPads:
    - Overview: iPads/index.md
    - Manual - API Setup: iPads/preparations.md

plugins:
  - search
  - jekyll-remote-theme
