site_name: Support extern
site_description: Haeufig gestellte Fragen und Anleitungen fuer die Nutzung unserer Dienste.
# site_url: https://example.org

docs_dir: docs
site_dir: site

theme:
  name: material
  language: de
  palette:
    - scheme: default
      primary: white
      accent: amber
  features:
    - navigation.sections
    - toc.integrate
    - search.highlight

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Office 365:
      - FAQs: office365/index.md
      - Anleitungen: office365/manuals.md
  - WebUntis:
      - FAQs: webuntis/index.md
      - Anleitungen: webuntis/manuals.md
      - Schüler Login: webuntis/students-login.md
      - Eltern Login: webuntis/parents-login.md
      - App Login: webuntis/app-login.md
  - iPads:
      - Inhalt: iPads/index.md
      - Einrichtung: iPads/setup.md
      - Problemlösung: iPads/help.md